name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run formatter
      run: cargo clippy --all --verbose --all-features -- -D warnings
    - name: Run Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --all --verbose
